on: push

jobs:
    okteto:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - run: kubectl --kubeconfig=okteto create cronjob hello --image=busybox --schedule="*/1 * * * *" -- echo "Hello World"
